### ISSUE TITLE
Issue with the height of the room card

### ISSUE THREAD

**Issue by ArianMoser** [ArianMoser/StreamTogether#12]
If you add a picture, it could be that the roomcard is a little bit smaller than the other ones (look at the screenshot attached) -> Join buttons are not on the same height anymore

![Picture of the RoomOverview](https://user-images.githubusercontent.com/31179977/39624770-cfe0fb7a-4f9a-11e8-8d1e-815ebda8529a.PNG)

**Comment by alexanderklapdor** [comment]
If a fixed size is awarded, then the pictures are distorted.
In addition, the cards are already different sizes because of the different lengths titles and descriptions.
